{{- if .Values.global.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.config.secret" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
type: Opaque
stringData: {{ .Values.settings }}
{{- end }}