apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gitlab.deploy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: ssh
  type: ClusterIP
  externalIPs:
    - {{ .Values.env.plain.ip }}
  selector:
    {{- include "gitlab.deploy.selectorLabels" . | nindent 4 }}
