{{- range $key, $value := .Values.db }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" $ }}-rest-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "deploy.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    rest: {{ $key }}
    {{- include "dbRestApi.deploy.selectorLabels" $ | nindent 4 }}
{{- end }}