{{- if .Values.backup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "deploy.backup.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    job-family: cron
    job-name: backup-drupal
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.schedule | quote }}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "deploy.serviceAccountName" $ }}-backup
          containers:
          - name: backup
            image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
            imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
            resources:
              {{- toYaml .Values.backup.resources | nindent 14 }}
            volumeMounts:
            - name: target
              mountPath: /mnt/target
              subPath: {{ include "deploy.backup.subPath" . }}
            - name: drupal-private
              mountPath: /mnt/source_private
              subPath: private
            - name: drupal-public
              mountPath: /mnt/source_public
              subPath: public
          volumes:
          - name: drupal-public
            persistentVolumeClaim:
              claimName: {{ include "deploy.fullname" . }}
          - name: drupal-private
            persistentVolumeClaim:
              claimName: {{ include "deploy.fullname" . }}
          - name: target
            persistentVolumeClaim:
              claimName: {{ include "deploy.backup.name" . }}
{{- end }}