{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deploy.backup.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backupStorage.size }}
  storageClassName: {{ .Values.backupStorage.className }}
{{- end }}