{{- if .Values.createConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  settings.php: |-
{{ .Values.settings | indent 4 }}
{{- end }}