{{- if .Values.import.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deploy.import.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.import.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: "backup.smb"
{{- end }}