{{- range $key, $value := .Values.rest.services }}
---
{{- if $.Values.rest.ingress.enabled -}}
{{- $fullName := include "deploy.fullname" $ -}}
{{- $svcPort := $.Values.rest.service.port -}}
{{- if and $.Values.rest.ingress.className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $.Values.rest.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $.Values.rest.ingress.annotations "kubernetes.io/ingress.class" $.Values.rest.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-rest-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "deploy.labels" $ | nindent 4 }}
  {{- with $.Values.rest.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $.Values.rest.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.rest.ingress.className }}
  {{- end }}
  {{- if $.Values.global.plain.baseUrl }}
  tls:
    - hosts:
        - {{ printf "%s.%s.%s" $key "rest" $.Values.global.plain.baseUrl | quote }}
      secretName: {{ printf "%s.%s.%s" $key "rest" $.Values.global.plain.baseUrl | quote }}
  {{- end }}
  rules:
    {{- if $.Values.global.plain.baseUrl }}
    - host: {{ printf "%s.%s.%s" $key "rest" $.Values.global.plain.baseUrl | quote }}
      http:
        paths:
          - path: {{ $.Values.rest.ingress.path }}
            {{- if and $.Values.rest.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $.Values.rest.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-rest-{{ $key }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-rest-{{ $key }}
              servicePort: {{ $svcPort }}
              {{- end }}
    {{- end }}
{{- end }}
{{- end }}