{{- if .Values.global.createSecret }}
{{- range $key, $value := .Values.rest.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.secrets" $ }}-{{ $key }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_PASS: {{ $value.dbPassword | b64enc }}
{{- end }}
{{- end }}