apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}-bdm
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bdm.service.type }}
  ports:
    - port: {{ .Values.bdm.service.port }}
      targetPort: bdm-http
      protocol: TCP
      name: bdm-http
  selector:
    {{- include "signavio.bdm.deploy.selectorLabels" . | nindent 4 }}
