# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  plain:
    environment: stage # production
    baseUrl: "mariadb.web3.lwb.local"
    dbExternal: true
    dbIP: "127.0.0.1" # setzen, wenn dbExternal: true
    dbPort: "3306"
    dbUser: "user"
    dbDatabase: "db"
    dbLogHost: "wolf.lwb.local"
    dbLogUser: "logger"
  secret:
    dbRootPassword: "changeme"
    dbPassword: "changeme"
    dbLogPassword: "changeme"
  imageCredentials: {}
  createSecret: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: "registry.gitlab.com/lwb-web/docker/library/extend/mariadb-backup"
  pullPolicy: Always
  tag: "3.17"

resources: {}
  #  limits:
  #    cpu: 1
  #    memory: 1Gi

storage:
  className: "backup.smb"
  size: 4Gi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}

tolerations: []

affinity: {}

backup:
  schedule: "0 21 * * *"
  system: "mariadb"
