{{- if .Values.global.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: registry.gitlab.com
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "gitlabPullSecret" . }}
{{- end }}