apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storage.className }}
  resources:
    requests:
      storage: {{ .Values.global.storage.size }}