{{- if not .Values.global.plain.dbExternal -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  extra.cnf: |-
{{ .Values.configuration | indent 4 }}
{{- end }}