apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "mariadb.deploy.selectorLabels" . | nindent 6 }}
