{{- if not .Values.global.plain.dbExternal -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}