{{- if .Values.global.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.secrets" . }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.global.secret.dbRootPassword | b64enc }}
  MYSQL_PASSWORD: {{ .Values.global.secret.dbPassword | b64enc }}
{{- if .Values.backup.enabled -}}
  DB_BACKUP_PASSWORD: {{ .Values.global.secret.dbPassword | b64enc }}
  LOG_PASSWORD: {{ .Values.global.secret.dbLogPassword | b64enc }}
{{- end}}
{{- end}}