{{- if .Values.backup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "deploy.backup.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    job-family: cron
    job-name: backup-gitlab
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.schedule | quote }}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "deploy.serviceAccountName" $ }}-backup
          containers:
          - name: backup
            image: bitnami/kubectl
            command: ["/bin/bash", "-c"]
            args:
              - POD_NAME=$(kubectl get pods -l tier=frontend -o=jsonpath='{.items[0].metadata.name}' -n {{ $.Release.Namespace }} --field-selector=status.phase=Running);
                kubectl exec $POD_NAME -n {{ $.Release.Namespace }} -c {{ $.Chart.Name }} -- bash -c 'gitlab-backup';
                exit 0;
          - name: copy
            image: alpine
            command: ["/bin/sh", "-c"]
            args:
              - cp /mnt/data/backups/*.tar /mnt/target/;
                cp /mnt/config/gitlab-secrets.json /mnt/target/;
                exit 0;
            volumeMounts:
            - name: target
              mountPath: /mnt/target
              subPath: {{ include "deploy.backup.subPath" . }}
            - name: data
              mountPath: /mnt/config
              subPath: config
            - name: data
              mountPath: /mnt/data
              subPath: data
          volumes:
          - name: target
            persistentVolumeClaim:
              claimName: {{ include "deploy.backup.name" . }}
          - name: data
            persistentVolumeClaim:
              claimName: {{ include "deploy.fullname" . }}
{{- end }}