apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy.serviceAccountName" . }}-backup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
