apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deploy.pvc.private" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.private }}