{{- if .Values.global.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.secrets" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
type: Opaque
data:
  {{- range .Values.env.secret }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end}}
{{- end}}