apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    job-family: cron
    job-name: db-backup
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.schedule | quote }}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "deploy.serviceAccountName" $ }}
          containers:
          - name: backup
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            volumeMounts:
            - name: backup
              mountPath: /mnt/backup
              subPath: {{ include "deploy.dbBackup.subPath" . }}
            env:
            {{- include "helpers.listDbBackupEnvVariables" . | indent 12 }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "deploy.secrets" . }}
                  key: MYSQL_PASSWORD
            - name: LOG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "deploy.secrets" . }}
                  key: LOG_PASSWORD
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: {{ include "deploy.fullname" . }}
