apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.backupStorage.size }}
  storageClassName: {{ .Values.global.backupStorage.className }}
